name: Node CI
on: [push, pull_request]
jobs:
  node-build:
    name: Install, lint, build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      #- run: yarn test # TODO: Add mocking database
